

#DHS & Other Agencies
DHS = ['Department of Homeland Security' , 'Federal Emergency Management Agency',
'Coast Guard', 'Customs and Border Protection', 'Border Patrol', 'Secret Service',
'National Operations Center', 'Homeland Defense',
'Immigration Customs Enforcement', 'Agent', 'Task Force',
'Central Intelligence Agency',
'Fusion Center',
'Drug Enforcement Agency',
'Secure Border Initiative', 'Federal Bureau of Investigation',
'Alcohol Tobacco and Firearms', 'U.S. Citizenship and Immigration Services',
'Federal Air Marshal Service', 'Transportation Security Administration',
'Air Marshal', 'Federal Aviation Administration', 'National Guard',
'Red Cross',
'United Nations'] 

#Domestic Security
Domestic = ['Assassination',
'Attack',
'Domestic security',
'Drill',
'Exercise',

'Cops',
'Law enforcement',
'Authorities',
'Disaster assistance',
'Disaster management',
'Domestic Nuclear Detection Office',
'National preparedness',
'Mitigation',
'Prevention',
'Response',
'Recovery',
'Dirty Bomb',
'Domestic nuclear detection',
'Emergency management',
'Emergency response',
'First responder',
'Homeland security',
'Maritime domain awareness',
'National preparedness initiative',
'Militia',
'Shooting',
'Shots fired',
'Evacuation',
'Deaths',
'Hostage',
'Explosion',
'Police',
'Disaster medical assistance team',
'Organized crime',
'Gangs',
'National security',
'State of emergency',
'Security',
'Breach',

'Threat',
'Standoff',
'SWAT',
'Screening',
'Lockdown',
'Bomb threat',
'Crash',
'Looting',
'Riot',
'Emergency Landing',
'Pipe bomb',
'Incident',
'Facility']

#HAZMAT & nuclear
HAZMAT = ['Hazmat',
'Nuclear',
'Chemical Spill',
'Suspicious package',
'Toxic',
'National laboratory',
'Nuclear facility',
'Nuclear threat',
'Cloud',
'Plume',
'Radiation',
'Radioactive',
'Leak',
'Biological infection',
'Chemical',
'Chemical burn',
'Biological',
'Epidemic',
'Hazardous',
'Hazardous material incident',
'Industrial spill',
'Infection',
'Powder',

'Gas',
'Spillover',
'Anthrax',
'Blister agent',
'Exposure',
'Burn',
'Nerve agent',
'Ricin',
'Sarin',
'North Korea']


#Health Concern + H1N1
Health = ['Outbreak',
'Contamination',
'Exposure',
'Virus',
'Evacuation',

'Bacteria',
'Recall',
'Ebola',
'Food Poisoning',
'Foot and Mouth',
'H5N1',

'Avian',
'Flu',
'Salmonella',
'Small Pox',
'Plague',
'Human to human',

'Human to animal',
'Influenza',
'Center for Disease Control',
'Drug Administration',
'Public Health',
'Toxic',
'Agro Terror',
'Tuberculosis',

'Agriculture',
'Listeria',
'Symptoms',
'Mutation',
'Resistant',
'Antiviral',
'Wave',
'Pandemic',
'Infection',
'Water/air borne',
'Sick',
'Swine',
'Pork',
'Strain',
'Quarantine',
'H1N1',
'Vaccine',
'Tamiflu',
'Norvo Virus',
'Epidemic',

'World Health Organization', 'Viral Hemorrhagic Fever',
'E. Coli']

#Infrastructure Security
Infrastructure = ['Infrastructure security',
'Airport',
'Critical Infrastructure & Key Resources',
'AMTRAK',
'Collapse',
'Computer infrastructure',
'Communications infrastructure',
'Telecommunications',
'Critical infrastructure',
'National infrastructure',
'Metro',
'WMATA',
'Airplane',
'Chemical fire',
'Subway',
'BART',
'MARTA',
'Port Authority',
'National Biosurveillance Integration Center',
'Transportation security',
'Grid',
'Power',
'Smart',
'Body scanner',
'Electric',
'Outage',
'Black out',
'Brown out',
'Port',
'Dock',
'Bridge',
'Canceled',
'Delays',
'Service disruption',
'Power lines']

#Southwest Border Violence
Southwest = ['Drug cartel',
'Violence',
'Gang',
'Drug',
'Narcotics',
'Cocaine',
'Marijuana',
'Heroin',
'Border',
'Mexico',
'Cartel',
'Southwest',
'Juarez',
'Sinaloa',
'Tijuana',
'Torreon',
'Yuma',
'Tucson',
'Decapitated',
'U.S. Consulate',
'Consular',
'El Paso',
'Fort Hancock',
'San Diego',
'Ciudad Juarez',
'Nogales',
'Sonora',
'Colombia',
'Mara salvatrucha',
'MS-13',
'Drug war',
'Mexican army',
'Methamphetamine',
'Cartel de Golfo',
'Gulf Cartel',
'La Familia',
'Reynose',
'Nuevo Leon',
'Narcos',
'Narco banners', 'Los Zetas',
'Shootout',
'Execution',
'Gunfight',
'Trafficking',
'Kidnap',
'Calderon',
'Reyosa',
'Bust',
'Tamaulipas',
'Meth Lab',
'Drug trade',
'Illegal immigrants',
'Smuggling',
'Matamoros',
'Michoacana',
'Guzman',
'Arellano-Felix',
'Beltran-Leyva',
'Barrio Azteca',
'Artistics Assassins',
'Mexicles',
'New Federation']

#Terrorism
Terrorism = ['Terrorism',
'Al Queda',
'Terror',
'Attack',
'Iraq',
'Afghanistan',
'Iran',
'Pakistan',
'Agro',
'Environmental terrorist',
'Eco terrorism',
'Conventional weapon',
'Target',
'Weapons grade',
'Dirty bomb',
'Enriched',
'Nuclear',
'Chemical weapon',
'Biological weapon',
'Ammonium nitrate',
'Improvised explosive device',
'Improvised Explosive Device',
'Abu Sayyaf',
'Hamas',
'Armed Revolutionary Forces Colombia',
'Irish Republican Army',
'Euskadi ta Askatasuna',
'Basque Separatists',
'Hezbollah',
'Tamil Tiger',
'Palestine Liberation Front',
'Palestine Libration Organization',
'Car bomb',
'Jihad',
'Taliban',
'Weapons cache',
'Suicide bomber',
'Suicide attack',
'Suspicious substance',
'Al Qaeda Arabian Peninsula',
'Al Qaeda in the Islamic Maghreb',
'Tehrik-i-Taliban Pakistan',
'Yemen',
'Pirates',
'Extremism',
'Somalia',
'Nigeria',
'Radicals',
'Al-Shabaab',
'Home grown',
'Plot',
'Nationalist',
'Recruitment',
'Fundamentalism',
'Islamist']


#Weather/Disaster/Emergency
Emergency = ['Emergency',
'Hurricane',
'Tornado',
'Twister',
'Tsunami',
'Earthquake',
'Tremor',
'Flood',
'Storm',
'Crest',
'Temblor',
'Extreme weather',
'Forest fire',
'Brush fire',
'Ice',
'Stranded',
'Help',
'Hail',
'Wildfire',
'Tsunami Warning Center',
'Magnitude',
'Avalanche',
'Typhoon',
'Shelter-in-place',
'Disaster',
'Snow',
'Blizzard',
'Sleet',
'Mudslide',
'Erosion',
'Power outage',
'Brown out',
'Warning',
'Watch',
'Lightening',
'Aid',
'Relief',
'Closure',
'Interstate',
'Burst',
'Emergency Broadcast System']

#Cyber Security
Cyber = ['Cyber security',
'Botnet',
'DDOS',
'Denial of service',
'Malware',
'Virus',
'Trojan',
'Keylogger',
'Cyber Command',
'2600',
'Spammer',
'Phishing',
'Rootkit',
'Phreaking',
'Cain and abel',
'Brute forcing',
'Mysql injection',
'Cyber attack',
'Cyber terror',
'Hacker',
'China',
'Conficker',
'Worm',
'Scammers',
'Social media']

#this will spit out all the words/lists in a big chunk:

allWords = DHS, Domestic, HAZMAT, Health, Infrastructure, Southwest, Terrorism, Emergency, Cyber

def somefunc(allWords):
    for i in allWords:
        print(i)




    









 
